### ISSUE TITLE
Przekreślenie pojawia się na przyciskach

### ISSUE THREAD

**Issue by robertkirsz** [robertkirsz/js-basics#1]
Przekreślenie powinno pojawiać się tylko na opisie przedmiotu

**Comment by GrzegorzStanczyk** [comment]
Ok zajmę się tym wieczorem.

**Comment by GrzegorzStanczyk** [comment]
Poprawione, proszę sprawdź poprawność.

**Comment by robertkirsz** [comment]
Wygląda dobrze, zamykam 👍
